"""Collects everything the assignment asks for into one folder (and optionally a zip).

The assignment asks for an ontology file, a short documentation note, and the prompts, scripts and
intermediate artefacts behind them. This copies all of that out of the working tree, leaving behind
caches, build files and anything else that only matters while developing.
"""
import shutil
import zipfile
from pathlib import Path
from typing import Any

import typer

EXCLUDED_NAMES = {"__pycache__", ".cache", ".work", ".git", ".venv", ".pytest_cache", ".ruff_cache"}
EXCLUDED_SUFFIXES = {".pyc", ".pyo", ".aux", ".fls", ".fdb_latexmk", ".out", ".synctex.gz"}
# Each group becomes a section of the manifest, in the order a reader should meet them.
GROUPS: list[dict[str, Any]] = [
    {"name": "The ontology", "paths": ["ontology"],
     "about": "aiact-merged.owl is the release file. It merges the hand-authored core (aiact-core.ttl), "
              "the alignments and the generated entities. aiact-with-examples.ttl adds the fictional test "
              "individuals and is the file to open in Protégé to watch the reasoner classify them."},
    {"name": "The documentation note", "paths": ["docs"],
     "about": "Two pages covering scope, the pipeline, modelling decisions, competency questions and "
              "validation, with the Protege screenshot behind the validation claim. docs/html is the "
              "browsable ontology documentation generated by pyLODE."},
    {"name": "Prompts", "paths": ["prompts"],
     "about": "Every prompt the pipeline sends to a model: extraction, the verification critic, and the two "
              "used to draft the competency questions and their SPARQL."},
    {"name": "Scripts", "paths": ["src", "schemas", "tests", "Makefile", "pyproject.toml", "uv.lock"],
     "about": "One module per pipeline stage in src/aiact_onto/, the Pydantic schemas the model output is "
              "constrained to, and the test suite. 'make all' rebuilds the ontology from the committed data."},
    {"name": "Configuration", "paths": ["config"],
     "about": "Which articles are in scope, which model and settings each stage uses, and the namespaces."},
    {"name": "Queries and shapes", "paths": ["queries", "shapes"],
     "about": "The competency questions as executable SPARQL, and the SHACL shapes that check every entity "
              "carries a label, a definition and a reference to the Act."},
    {"name": "Intermediate artefacts", "paths": ["data"],
     "about": "Every stage's output, in order: the EUR-Lex snapshot, the chunked articles, the raw extraction, "
              "the verified records, and the curation decision log with the entities it produced."},
    {"name": "Reports", "paths": ["reports"],
     "about": "Validation results, the SHACL and ROBOT reports, diagrams of the class hierarchy and of what "
              "the reasoner inferred, and the report on what the review step changed."},
    {"name": "Repository", "paths": ["README.md", "LICENSE"],
     "about": "The project README and licence."},
]


def wanted(path: Path) -> bool:
    """Says whether a file belongs in the bundle.

    Args:
        path (Path): The file or directory.

    Returns:
        bool: False for caches, build files and empty placeholders.
    """
    if any(part in EXCLUDED_NAMES for part in path.parts):
        return False
    if path.suffix in EXCLUDED_SUFFIXES or path.name == ".gitkeep":
        return False
    return not (path.is_file() and path.stat().st_size == 0)


def copy(source: Path, destination: Path) -> list[Path]:
    """Copies a file or a whole directory, skipping anything unwanted.

    Args:
        source (Path): The file or directory to copy.
        destination (Path): Where it should land.

    Returns:
        list[Path]: The files written, relative to the bundle root.
    """
    if not source.exists():
        return []
    if source.is_file():
        if not wanted(source):
            return []
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)
        return [destination]

    written = []
    for item in sorted(source.rglob("*")):
        if item.is_dir() or not wanted(item):
            continue
        target = destination / item.relative_to(source)
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(item, target)
        written.append(target)
    return written


def size_of(paths: list[Path]) -> str:
    """Returns the total size of the given files, in KB or MB."""
    total = sum(p.stat().st_size for p in paths)
    return f"{total / 1_048_576:.1f} MB" if total >= 1_048_576 else f"{total / 1024:.0f} KB"


def manifest(groups: list[tuple[dict[str, Any], list[Path]]], out: Path) -> Path:
    """Writes a manifest so a reader knows what each folder holds.

    Args:
        groups (list[tuple[dict[str, Any], list[Path]]]): Each group with the files it contributed.
        out (Path): The bundle root.

    Returns:
        Path: The manifest that was written.
    """
    lines = [
        "# Submission contents",
        "",
        "Assembled by `make package` (`src/aiact_onto/package.py`) from the project repository.",
        "",
        "## Start here",
        "",
        "- `docs/documentation.pdf` — the two-page note.",
        "- `ontology/aiact-merged.owl` — the ontology.",
        "- `ontology/aiact-with-examples.ttl` — the same ontology plus test individuals; open this one in",
        "  Protégé and start HermiT to see them classified.",
        "- `reports/curation_report.md` — what the human-in-the-loop review changed, and why it mattered.",
        "",
    ]
    for group, files in groups:
        if not files:
            continue
        paths = ", ".join(f"`{p}`" for p in group["paths"] if (out / p).exists())
        lines += [f"## {group['name']}", "",
                  f"{group['about']}", "",
                  f"{paths} — {len(files)} files, {size_of(files)}", ""]
    target = out / "MANIFEST.md"
    target.write_text("\n".join(lines), encoding="utf-8")
    return target


app = typer.Typer(add_completion=False, help="Collect the assignment outputs into one folder.")


@app.command()
def main(
    out: Path = typer.Option(Path("output"), "--out", help="Folder to write the bundle into."),
    archive: bool = typer.Option(False, "--zip", help="Also write <out>.zip beside the folder."),
    force: bool = typer.Option(False, "--force", help="Replace the folder if it already exists."),
) -> None:
    """Copies the ontology, the note and everything behind them into one folder."""
    if out.exists():
        if not force:
            raise typer.BadParameter(f"{out} already exists; pass --force to replace it")
        shutil.rmtree(out)

    collected = []
    for group in GROUPS:
        files: list[Path] = []
        for path in group["paths"]:
            files.extend(copy(Path(path), out / path))
        collected.append((group, files))

    total = [f for _, files in collected for f in files]
    manifest(collected, out)
    print(f"{len(total)} files, {size_of(total)} in {out}")

    if archive:
        bundle = out.with_suffix(".zip")
        with zipfile.ZipFile(bundle, "w", zipfile.ZIP_DEFLATED) as zipped:
            for file in sorted(out.rglob("*")):
                if file.is_file():
                    zipped.write(file, file.relative_to(out.parent))
        print(f"{bundle} ({bundle.stat().st_size / 1_048_576:.1f} MB)")


if __name__ == "__main__":
    app()
